[server]
headless = true
port = 8000
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#4285F4" 
backgroundColor="#1e1e1e"
secondaryBackgroundColor="#2d2d2d"
textColor="#ffffff"
font="sans serif"